export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const ORDER_BY = 'ORDER_BY';
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND';